[package]
authors = ["Logan Buckley <logan.buckley@gmail.com>"]
name = "logos"
version = "0.1.0"

[[bin]]
name = "logos"
path = "src/main.rs"

[dependencies]
combine = "2.3.2"
itertools = "0.6.0"
lazy_static = "0.2.8"
prettytable-rs = "0.6.6"
rmp-serde = "0.13.3"
rusqlite = "0.12.0"
rustyline = "1.0.0"
serde = "1.0.8"
serde_derive = "1.0.8"
uuid = { version = "0.5.0", features = ["v4"] }

[dependencies.chrono]
features = ["serde"]
version = "0.3.1"
