[package]
authors = ["Logan Buckley <logan.buckley@gmail.com>"]
name = "logos"
version = "0.1.0"

[[bin]]
name = "logos"
path = "src/main.rs"

[dependencies]
chrono = "0.3.1"
combine = "2.3.2"
itertools = "0.6.0"
lazy_static = "0.2.8"
prettytable-rs = "0.6.6"
rustyline = "1.0.0"
